export enum OrderStatus {
    PENDING = 'PENDING',
    PLACED = 'PLACED',
    BILLED = 'BILLED',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    READY_TO_SHIP = 'READY_TO_SHIP',
    CANCELLED = 'CANCELLED',
  }